version: '3.8'

services:
  scrapbook-dev:
    build:
      context: ./website
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/docs:ro
      - ./website:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FAST_REFRESH=true
    command: npm start
    restart: unless-stopped

networks:
  default:
    name: scrapbook-network